FoodOrdering/Admin/Controllers/AdminCategoryController.cs
using FoodOrdering.Constants;
using FoodOrdering.Dto;
using FoodOrdering.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FoodOrdering.Admin.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class AdminCategoryController : Controller
    {
        private readonly ICategoryService categoryService;

        public AdminCategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        public IActionResult Index()
        {
            return View("~/Admin/Views/Category/Index.cshtml", categoryService.GetAll());
        }

        public async Task<IActionResult> Create(CategoryDto category)
        {
            if (ModelState.IsValid)
            {
                await categoryService.Create(category);
                return RedirectToAction("Index");

            }
            return View("~/Admin/Views/Category/Create.cshtml", category);

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var category = categoryService.GetById(id);
            if (category == null)
                return NotFound();
            EditCategoryDto editCategory = new()
            {
                Id = category.Id,
                Name = category.Name,
                IsActive = category.IsActive,
                ImgName = category.ImgeUrl
            };

            return View("~/Admin/Views/Category/Edit.cshtml", editCategory);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditCategoryDto category)
        {
            if (ModelState.IsValid)
            {
                await categoryService.Update(category);
                return RedirectToAction("Index");

            }
            return View("~/Admin/Views/Category/Edit.cshtml", category);
        }
        public IActionResult Delete(int id)
        {
            categoryService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

FoodOrdering/Admin/Controllers/AdminOrdersController.cs
using FoodOrdering.Constants;
using FoodOrdering.Dto;
using FoodOrdering.Models;
using FoodOrdering.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FoodOrdering.Admin.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class AdminOrdersController : Controller
    {
        private readonly IOrderService _orderService;

        public AdminOrdersController(IOrderService orderService)
        {
            _orderService = orderService;
        }
        public async Task<IActionResult> DisplayAll()
        {
            var orders=await _orderService.GetOrders();
            return View("~/Admin/Views/AdminOrders/Index.cshtml",orders);
        }
        public IActionResult OrderDetails(int orderId)
        {
            var orders = _orderService.GetOrderDetails(orderId);
            return View("~/Admin/Views/AdminOrders/OrderDetails.cshtml",orders);
        }
        public async Task<IActionResult> UpdateOrderStatus(int orderId)
        {
            var order = _orderService.GetOrderById(orderId);
            if (order == null)
                throw new Exception("No order Found");

            var orderStatusList = (await _orderService.GetOrderStatuses()).Select(orderStatus =>
            {
                return new SelectListItem
                {
                    Value = orderStatus.Id.ToString(),
                    Text = orderStatus.StatusName,
                    Selected = orderStatus.Id == order.OrderStatusId
                };
            });
            var data = new UpdateOrderStatusModel()
            {
                OrderId = orderId,
                orderStatusId=order.OrderStatusId,
                OrderStatusNames=orderStatusList,

            };
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateOrderStatus(UpdateOrderStatusModel data)
        {
            try
            {
                //if (!ModelState.IsValid)
                //{
                //    var orderStatusList = (await _orderService.GetOrderStatuses()).Select(orderStatus =>
                //    {
                //        return new SelectListItem
                //        {
                //            Value = orderStatus.Id.ToString(),
                //            Text = orderStatus.StatusName,
                //            Selected = orderStatus.Id == data.OrderId
                //        };
                //    });
                //    return View(data);
                //}
                await _orderService.ChangeOrderStatus(data);
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false });

            }
            //return RedirectToAction(nameof(DisplayAll));

            
        }
    }
}

FoodOrdering/Admin/Controllers/AdminProductController.cs
using FoodOrdering.Constants;
using FoodOrdering.Dto;
using FoodOrdering.Models;
using FoodOrdering.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Foody.Admin.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class AdminProductController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;

        public AdminProductController(IProductService productService,ICategoryService categoryService)
        {
            this.productService = productService;
            this.categoryService = categoryService;
            categoryService = categoryService;
        }
        public IActionResult Index()
        {
            List<Product> products = productService.GetAll();
            return View("~/Admin/Views/AdminProduct/Index.cshtml",products);
        }
        public IActionResult Details(int id)
        {
            return View("~/Admin/Views/AdminProduct/Details.cshtml",productService.GetById(id));
        }
        public async Task<IActionResult> Create(ProductDto productDto)
        {
            ViewBag.Cateogries = categoryService.GetAll();
            if (ModelState.IsValid)
            {
                await productService.AddProduct(productDto);
                return RedirectToAction("Index");
            }
            return View("~/Admin/Views/AdminProduct/Create.cshtml", productDto);

        }
        public IActionResult Search(string name) 
        {

            List<Product> ps = productService.Search(name);
            return View("~/Admin/Views/AdminProduct/Index.cshtml", ps);
        }
        [HttpGet]
        public IActionResult Edit(int id) {
             var product = productService.GetById(id);
            ProductDto productDto = new()
            {
                Name = product.Name,
                Description = product.Description,
                IsActive = product.IsActive,
                Price = product.Price,
                Quantity = product.Quantity,
                CategoryId = product.CategoryId,
                ImgName = product.ImgeUrl
            };
            ViewBag.categories=categoryService.GetAll();
             return View("~/Admin/Views/AdminProduct/Edit.cshtml",productDto);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(int id,ProductDto product) {
            if (ModelState.IsValid)
            {
                await productService.Edit(id, product);
                return RedirectToAction("Index",productService.GetAll());
            }
            return View("~/Admin/Views/AdminProduct/Edit.cshtml",product);

        }
        public ActionResult Delete(int id) {
            productService.Delete(id);
          return RedirectToAction("Index");
        }


    }
}

FoodOrdering/Admin/Controllers/ManageUsersController.cs
using FoodOrdering.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FoodOrdering.Admin.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class ManageUsersController : Controller
    {
        private readonly IUserService _userService;

        public ManageUsersController(IUserService userService)
        {
             _userService = userService;
        }
        public IActionResult Index()
        {
            var users=_userService.GetAllUser();
            return View("~/Admin/Views/Users/Index.cshtml",users);
        }
        public IActionResult Delete(string id)
        {
            _userService.DeleteAccount(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

FoodOrdering/Admin/Views/Index.cshtml
@model StatisticData
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Admin Dashbord</h2>


<div class="page-body">
    <div class="row">
        <!-- card1 start -->
        <div class="col-md-6 col-xl-3">
            <div class="card widget-card-1">
                <a class="card-block-small" asp-controller="AdminCategory">
                    <i class="icofont icofont-muffin bg-c-blue card1-icon"></i>
                    <span class="text-c-blue f-w-600">Categories</span>
                    <h4>@Model.CategoriesCount</h4>
                    <div>
                    <span class="f-left m-t-10 text-muted">
                    <i class="text-c-blue f-16 icofont icofont-eye-alt m-r-10"></i>View Details
                    </span>
                    </div>
                </a>
            </div>
        </div>
        <!-- card1 end -->
        <!-- card1 start -->
        <div class="col-md-6 col-xl-3">
            <div class="card widget-card-1">
                <a class="card-block-small" asp-controller="AdminProduct" >
                    <i class="icofont icofont-fast-food bg-c-pink card1-icon"></i>
                    <span class="text-c-pink f-w-600">Products</span>
                    <h4>@Model.ProductsCount</h4>
                    <div>
                        <span class="f-left m-t-10 text-muted">
                            <i class="text-c-pink f-16 icofont icofont-eye-alt m-r-10"></i>View Details
                        </span>
                    </div>
                </a>
            </div>
        </div>
        <!-- card1 end -->
        <!-- card1 start -->
        <div class="col-md-6 col-xl-3">
            <div class="card widget-card-1">
                <a class="card-block-small" asp-controller="ManageUsers">
                    <i class="icofont icofont-user bg-c-green card1-icon"></i>
                    <span class="text-c-green f-w-600">Users</span>
                    <h4>@Model.UsersCount</h4>
                    <div>
                        <span class="f-left m-t-10 text-muted">
                            <i class="text-c-green f-16 icofont icofont-eye-alt m-r-10"></i>View Details
                        </span>
                    </div>
                </a>
            </div>
        </div>
        <!-- card1 end -->
        <!-- card1 start -->
        <div class="col-md-6 col-xl-3">
            <div class="card widget-card-1">
                <a class="card-block-small" asp-controller="AdminOrders" asp-action="DisplayAll">
                    <i class="icofont icofont-spoon-and-fork bg-c-yellow card1-icon"></i>
                    <span class="text-c-yellow f-w-600">Total Orders</span>
                    <h4>@Model.OrdersCount</h4>
                    <div>
                        <span class="f-left m-t-10 text-muted">
                            <i class="text-c-yellow f-16 icofont icofont-eye-alt m-r-10"></i>View Details
                        </span>
                    </div>
                </a>
            </div>
        </div>
        <!-- card1 end -->
        <!-- card1 start -->
        <div class="col-md-6 col-xl-3">
            <div class="card widget-card-1">
                <div class="card-block-small">
                    <i class="icofont icofont-money-bag bg-c-green card1-icon"></i>
                    <span class="text-c-green f-w-600">sold Amount</span>
                    <h4>@Model.SoldAmount EGY</h4>
                    <div>
                        <span class="f-left m-t-10 text-muted">
                            <i class="text-c-green f-16 icofont icofont-eye-alt m-r-10"></i>View Details
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>